cors_origin_regex: "http://localhost:\\d+$"

jwt_secret: dev-secret-change-me
jwt_ttl_seconds: 300

redis_url: redis://localhost:6379/0
huddle_ttl_seconds: 3600

media_server_url: http://localhost:7001


