cors_origins:
  - http://localhost:8000
  - http://127.0.0.1:8000

jwt_secret: dev-secret-change-me
jwt_ttl_seconds: 300

sdp_ws_base: ws://localhost:3000/sdp
redis_url: redis://localhost:6379/0
huddle_ttl_seconds: 3600


